### ISSUE TITLE
找不到对应功能

### ISSUE THREAD

**Issue by maoruibin001** [NightCatSama/NightCat#3]
我在https://nightcat.win/这个网址找不到你说描述的对应功能，只有动画，不能登录、注册和邮箱认证，我准备参考小你的代码，谢谢。

**Comment by NightCatSama** [comment]
噗，不好意思，因为不打算用react了，计划使用vue重构，所以我就去掉了所有页面，而且最近有点忙还没开始动工。

如果只是后台功能的话，可以直接看代码：

登录、注册：
1. 接口代码 `./controllers/sign.js`
3. jwt加密和验证 `./common/sign.js`
2. 添加、查询用户信息 `./proxy/user.js`

邮箱认证：
1. 发送方法 `./common/mail.js`
2. 相关设置 `./config/` 中的 `mail_opts` 属性

文档没有及时修改，实在抱歉。

**Comment by maoruibin001** [comment]
好的，谢谢。
