### ISSUE TITLE
数据库文件能否提供下

### ISSUE THREAD

**Issue by mafeifan** [NightCatSama/NightCat#4]
项目不错！想在本地运行下该项目，没有找到数据库文件，方便提供下吗？

**Comment by NightCatSama** [comment]
只要在本地跑mangodb就行了

我在windows上是用.cmd命令脚本运行的

```cmd
:: 定位到C盘
cd c:/
 
:: 切换到mongodb的数据库目录
cd Program Files\MongoDB\Server\3.4\bin
 
:: 配置mongodb的文档存储目录
mongod --dbpath "F:\Mongodb\data"
```

**Comment by mafeifan** [comment]
谢谢，运行成功了。还有一个问题，我在后台注册帐号后，添加文章提示没有权限，我只好手动改数据库了
superAdmin和admin都改了为true。

**Comment by mafeifan** [comment]
另外后台添加文章cover 封面图是填图片路径吗？做成上传更友好一点

**Comment by NightCatSama** [comment]
是的，超级管理员superAdmin需要手动修改数据库，admin可以由superAdmin在用户管理里添加。

封面图当初考虑不周（懒）就没弄那么复杂，以后可能会改成支持图片路径或上传两种吧，近期应该不会改

**Comment by mafeifan** [comment]
好的，谢谢了
