### ISSUE TITLE
Github 三方登陆挂了。。

### ISSUE THREAD

**Issue by gotexis** [NightCatSama/NightCat#9]
看到这个项目很好，想学习一下三方登陆怎么实现，不过试着登陆下你的博客，没成功 :)

作者可否调查一下:)

**Comment by NightCatSama** [comment]
我看了一下，第三方登录流程还是正确的。

但是不知道为什么 github 返回的数据不给 email 了，然后我这边会显示`请先在 github 中设置公开邮箱`。

但是因为我 ContentType 没设置对，所以显示乱码才看起来像是挂了。

<https://github.com/NightCatSama/NightCat/commit/3d5dcad63587945326f754c5ac1126397d1268b1>

**Comment by NightCatSama** [comment]
github 好像也没错，是我自己的账号没设置公开邮箱。。。

![image](https://user-images.githubusercontent.com/13888962/54910572-9003d580-4f27-11e9-8189-c7b84f09fad5.png)

我把这个设置上就zheng正常了。
